kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: meat-helper
  namespace: demo-meat-helper
  labels:
    app: meat-helper
    app.kubernetes.io/component: meat-helper
    app.kubernetes.io/instance: meat-helper
    app.kubernetes.io/name: meat-helper
    app.kubernetes.io/part-of: meat-helper
spec:
  lookupPolicy:
    local: false
  tags:
    - name: demo
      annotations:
        openshift.io/imported-from: 'quay.io/stauil/quarkus-meat-helper:demo'
      from:
        kind: DockerImage
        name: 'quay.io/stauil/quarkus-meat-helper:demo'
      importPolicy:
        insecure: true
        importMode: Legacy
      referencePolicy:
        type: Local