apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meat-helper
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workload/application/overlays/default
    repoURL: https://github.com/na-launch/gitops-sample-app.git
    targetRevision: main
  syncPolicy: {}